# Generated by Django 3.2.18 on 2024-05-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentApp', '0002_room_room_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('property', 'room_number')},
        ),
    ]
