# Generated by Django 3.2.18 on 2024-05-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentApp', '0003_alter_room_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_kitchens',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(to='apartmentApp.Amenity'),
        ),
        migrations.AddField(
            model_name='room',
            name='features',
            field=models.ManyToManyField(to='apartmentApp.Feature'),
        ),
    ]
