# Generated by Django 3.2.18 on 2024-05-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentApp', '0004_auto_20240503_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_mates',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='occupancy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
