# Generated by Django 3.2.18 on 2024-05-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentApp', '0005_auto_20240503_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_mates',
            new_name='property_numPeopleCurrent',
        ),
        migrations.AddField(
            model_name='room',
            name='property_num_bed_Rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
